version: '0.1'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - base_network

  web:
     build: .
     env_file:
       - .env
     ports:
       - "8000:8000"
     command: poetry run python main.py
     networks:
       - base_network
     depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy

  minio:
    image: minio/minio
    env_file:
      - .env
    volumes:
      - ./minio_data:/var/lib/minio/data
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - "9000"
      - "9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: server --console-address ":9001" /data

networks:
  base_network:
volumes:
  minio_data:
